// Generated by scripts/sync-diagnosis-results.mjs. Do not edit.
import { query } from "@/features/admin/server/db";
import type { DiagnosisTypeCode } from "./diagnosis.dto";
export type LatestDiagnosisResultRow = {
    run_id: string;
    result_id: string;
    type_code: DiagnosisTypeCode;
    type_name: string;
    summary: string | null;
    stability_score: number;
    challenge_score: number;
    teamwork_axis_percent: number;
    execution_axis_percent: number;
    principle_axis_percent: number;
    stability_axis_percent: number;
    strengths: string[];
    weaknesses: string[];
    raw_result: Record<string, unknown> | null;
    completed_at: Date | string;
};
export async function findLatestDiagnosisResultForUser(userId: string) {
    const result = await query<LatestDiagnosisResultRow>(`
      SELECT
        runs.id AS run_id,
        results.id AS result_id,
        personality_types.code AS type_code,
        personality_types.name AS type_name,
        results.summary,
        results.stability_score,
        results.challenge_score,
        results.stability_axis_percent,
        results.teamwork_axis_percent,
        results.execution_axis_percent,
        results.principle_axis_percent,
        results.strengths,
        results.weaknesses,
        results.raw_result,
        COALESCE(runs.completed_at, results.created_at) AS completed_at
      FROM public.diagnosis_results results
      JOIN public.diagnosis_runs runs
        ON runs.id = results.diagnosis_run_id
      JOIN public.personality_types personality_types
        ON personality_types.id = results.personality_type_id
      JOIN public.users users
        ON users.id = $1
      WHERE results.user_id = $1
         OR runs.user_id = $1
         OR EXISTS (
           SELECT 1
           FROM public.diagnosis_login_conversions conversions
           WHERE conversions.diagnosis_result_id = results.id
             AND conversions.user_id = $1
         )
      ORDER BY
        (results.id = users.selected_diagnosis_result_id) DESC,
        runs.completed_at DESC NULLS LAST,
        results.created_at DESC,
        results.id DESC
      LIMIT 1
    `, [userId]);
    return result.rows[0];
}
export async function findDiagnosisResultForUser(userId: string, resultId: string) {
    const result = await query<LatestDiagnosisResultRow>(`
      SELECT
        runs.id AS run_id,
        results.id AS result_id,
        personality_types.code AS type_code,
        personality_types.name AS type_name,
        results.summary,
        results.stability_score,
        results.challenge_score,
        results.stability_axis_percent,
        results.teamwork_axis_percent,
        results.execution_axis_percent,
        results.principle_axis_percent,
        results.strengths,
        results.weaknesses,
        results.raw_result,
        COALESCE(runs.completed_at, results.created_at) AS completed_at
      FROM public.diagnosis_results results
      JOIN public.diagnosis_runs runs
        ON runs.id = results.diagnosis_run_id
      JOIN public.personality_types personality_types
        ON personality_types.id = results.personality_type_id
      WHERE results.id = $2
        AND (
          results.user_id = $1
          OR runs.user_id = $1
          OR EXISTS (
            SELECT 1
            FROM public.diagnosis_login_conversions conversions
            WHERE conversions.diagnosis_result_id = results.id
              AND conversions.user_id = $1
          )
        )
      LIMIT 1
    `, [userId, resultId]);
    return result.rows[0];
}
export async function findJobCategoriesForPersonalityType(code: DiagnosisTypeCode) {
    const result = await query<{
        name: string;
        reason: string;
    }>(`
      SELECT categories.name, mappings.reason
      FROM public.personality_job_category_mappings mappings
      JOIN public.personality_types personality_types
        ON personality_types.id = mappings.personality_type_id
      JOIN public.job_categories categories
        ON categories.id = mappings.job_category_id
      WHERE personality_types.code = $1
        AND categories.is_active = TRUE
      ORDER BY
        mappings.fit_weight DESC,
        mappings.sort_order ASC,
        categories.sort_order ASC
      LIMIT 6
    `, [code]);
    return result.rows;
}
export async function findDiagnosisPercentile(resultId: string, typeCode: DiagnosisTypeCode, userId: string) {
    const result = await query<{
        top_percent: number | string | null;
        sample_size: number | string;
    }>(`
      WITH target AS (
        SELECT
          CASE $2
            WHEN 'stability' THEN results.stability_axis_percent
            WHEN 'challenge' THEN 100 - results.stability_axis_percent
            WHEN 'teamwork' THEN results.teamwork_axis_percent
            WHEN 'individual' THEN 100 - results.teamwork_axis_percent
            WHEN 'execution' THEN results.execution_axis_percent
            WHEN 'planning' THEN 100 - results.execution_axis_percent
            WHEN 'principle' THEN results.principle_axis_percent
            WHEN 'flexibility' THEN 100 - results.principle_axis_percent
          END AS trait_score
        FROM public.diagnosis_results results
        WHERE results.id = $1
      ),
      registered_results AS (
        SELECT DISTINCT ON (owners.user_id)
          owners.user_id,
          results.stability_axis_percent,
          results.teamwork_axis_percent,
          results.execution_axis_percent,
          results.principle_axis_percent
        FROM public.diagnosis_results results
        JOIN public.diagnosis_runs runs
          ON runs.id = results.diagnosis_run_id
        CROSS JOIN LATERAL (
          SELECT COALESCE(
            results.user_id,
            runs.user_id,
            (
              SELECT conversions.user_id
              FROM public.diagnosis_login_conversions conversions
              WHERE conversions.diagnosis_result_id = results.id
              ORDER BY conversions.created_at DESC
              LIMIT 1
            )
          ) AS user_id
        ) owners
        JOIN public.users users
          ON users.id = owners.user_id
         AND users.status = 'active'
        WHERE owners.user_id <> $3::uuid
        ORDER BY
          owners.user_id,
          (results.id = users.selected_diagnosis_result_id) DESC,
          COALESCE(runs.completed_at, results.created_at) DESC,
          results.id DESC
      ),
      peers AS (
        SELECT
          CASE $2
            WHEN 'stability' THEN stability_axis_percent
            WHEN 'challenge' THEN 100 - stability_axis_percent
            WHEN 'teamwork' THEN teamwork_axis_percent
            WHEN 'individual' THEN 100 - teamwork_axis_percent
            WHEN 'execution' THEN execution_axis_percent
            WHEN 'planning' THEN 100 - execution_axis_percent
            WHEN 'principle' THEN principle_axis_percent
            WHEN 'flexibility' THEN 100 - principle_axis_percent
          END AS trait_score
        FROM registered_results
      )
      SELECT
        CASE
          WHEN COUNT(*) = 0 THEN NULL
          ELSE LEAST(
            100,
            GREATEST(
              1,
              CEIL(
                100.0 * (
                  COUNT(*) FILTER (
                    WHERE peers.trait_score > (SELECT trait_score FROM target)
                  ) + 1
                ) / (COUNT(*) + 1)
              )
            )
          )::integer
        END AS top_percent,
        COUNT(*)::integer AS sample_size
      FROM peers
    `, [resultId, typeCode, userId]);
    const row = result.rows[0];
    return {
        topPercent: row?.top_percent == null ? null : Number(row.top_percent),
        sampleSize: Number(row?.sample_size || 0),
    };
}
export async function countPreviousDiagnosisResults(userId: string, currentResultId: string) {
    const result = await query<{
        result_count: number | string;
    }>(`
      SELECT COUNT(DISTINCT results.id)::integer AS result_count
      FROM public.diagnosis_results results
      JOIN public.diagnosis_runs runs
        ON runs.id = results.diagnosis_run_id
      WHERE results.id <> $2::uuid
        AND (
          results.user_id = $1::uuid
          OR runs.user_id = $1::uuid
          OR EXISTS (
            SELECT 1
            FROM public.diagnosis_login_conversions conversions
            WHERE conversions.diagnosis_result_id = results.id
              AND conversions.user_id = $1::uuid
          )
        )
    `, [userId, currentResultId]);
    return Number(result.rows[0]?.result_count || 0);
}
export async function findRecommendedInstitutions(typeCode: DiagnosisTypeCode, limit: number) {
    const result = await query<{
        id: string;
        name: string;
    }>(`
      WITH mapped_categories AS (
        SELECT categories.name
        FROM public.personality_job_category_mappings mappings
        JOIN public.personality_types personality_types
          ON personality_types.id = mappings.personality_type_id
        JOIN public.job_categories categories
          ON categories.id = mappings.job_category_id
        WHERE personality_types.code = $1
          AND categories.is_active = TRUE
        ORDER BY mappings.fit_weight DESC, mappings.sort_order ASC
        LIMIT 6
      )
      SELECT institutions.id, institutions.name
      FROM public.job_postings postings
      JOIN public.public_institutions institutions
        ON institutions.id = postings.institution_id
      JOIN mapped_categories
        ON POSITION(
          REGEXP_REPLACE(mapped_categories.name, '[[:space:]·.]', '', 'g')
          IN REGEXP_REPLACE(COALESCE(postings.ncs_category, ''), '[[:space:]·.]', '', 'g')
        ) > 0
      WHERE postings.is_active = TRUE
        AND (postings.application_end_at IS NULL OR postings.application_end_at >= NOW())
        AND (
          postings.employment_type = '정규직'
          OR (
            postings.employment_type ILIKE '%정규%'
            AND postings.employment_type NOT ILIKE '%비정규%'
          )
        )
        AND COALESCE(
          postings.application_start_at,
          postings.announcement_at,
          postings.created_at
        ) < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
        AND COALESCE(
          postings.application_end_at,
          'infinity'::timestamptz
        ) >= DATE_TRUNC('month', CURRENT_DATE)
      GROUP BY institutions.id, institutions.name
      ORDER BY COUNT(DISTINCT postings.id) DESC, institutions.name ASC
      LIMIT $2
    `, [typeCode, limit]);
    return result.rows;
}
export async function findMonthlyHiringByPersonalityType(typeCode: DiagnosisTypeCode) {
    const result = await query<{
        name: string;
        posting_count: number | string;
        total_count: number | string;
    }>(`
      WITH mapped_categories AS (
        SELECT categories.id, categories.name, mappings.fit_weight, mappings.sort_order
        FROM public.personality_job_category_mappings mappings
        JOIN public.personality_types personality_types
          ON personality_types.id = mappings.personality_type_id
        JOIN public.job_categories categories
          ON categories.id = mappings.job_category_id
        WHERE personality_types.code = $1
          AND categories.is_active = TRUE
        ORDER BY mappings.fit_weight DESC, mappings.sort_order ASC
        LIMIT 6
      ),
      matched_postings AS (
        SELECT
          postings.id,
          mapped_categories.id AS job_category_id,
          mapped_categories.name,
          mapped_categories.fit_weight,
          mapped_categories.sort_order
        FROM public.job_postings postings
        JOIN mapped_categories
          ON POSITION(
            REGEXP_REPLACE(mapped_categories.name, '[[:space:]·.]', '', 'g')
            IN REGEXP_REPLACE(COALESCE(postings.ncs_category, ''), '[[:space:]·.]', '', 'g')
          ) > 0
        WHERE postings.is_active = TRUE
          AND (
            postings.application_end_at IS NULL
            OR postings.application_end_at >= NOW()
          )
          AND (
            postings.employment_type = '정규직'
            OR (
              postings.employment_type ILIKE '%정규%'
              AND postings.employment_type NOT ILIKE '%비정규%'
            )
          )
          AND COALESCE(
            postings.application_start_at,
            postings.announcement_at,
            postings.created_at
          ) < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
          AND COALESCE(
            postings.application_end_at,
            'infinity'::timestamptz
          ) >= DATE_TRUNC('month', CURRENT_DATE)
      ),
      category_counts AS (
        SELECT
          mapped_categories.id,
          mapped_categories.name,
          mapped_categories.fit_weight,
          mapped_categories.sort_order,
          COUNT(DISTINCT matched_postings.id)::integer AS posting_count
        FROM mapped_categories
        LEFT JOIN matched_postings
          ON matched_postings.job_category_id = mapped_categories.id
        GROUP BY
          mapped_categories.id,
          mapped_categories.name,
          mapped_categories.fit_weight,
          mapped_categories.sort_order
      ),
      ranked_counts AS (
        SELECT
          category_counts.*,
          ROW_NUMBER() OVER (
            ORDER BY posting_count DESC, fit_weight DESC, sort_order ASC
          ) AS display_rank
        FROM category_counts
        WHERE posting_count > 0
      )
      SELECT
        ranked_counts.name,
        ranked_counts.posting_count,
        (SELECT COUNT(DISTINCT id)::integer FROM matched_postings) AS total_count
      FROM ranked_counts
      ORDER BY ranked_counts.display_rank ASC
    `, [typeCode]);
    return {
        totalCount: Number(result.rows[0]?.total_count || 0),
        categories: result.rows.map((row) => ({
            name: row.name,
            count: Number(row.posting_count || 0),
        })),
    };
}
