// Generated by scripts/sync-diagnosis-results.mjs. Do not edit.
import { DiagnosisResultResponseDto } from "./diagnosis.dto";
import type { DiagnosisTypeCode } from "./diagnosis.dto";
import { findJobCategoriesForPersonalityType, findLatestDiagnosisResultForUser } from "./diagnosis.repository";
type AxisCode = "stability" | "teamwork" | "execution" | "principle";
type AxisScores = Record<AxisCode, number>;
type TraitScores = Record<DiagnosisTypeCode, number>;
type AxisDefinition = {
    code: AxisCode;
    leftCode: DiagnosisTypeCode;
    rightCode: DiagnosisTypeCode;
    leftLabel: string;
    rightLabel: string;
};
export const PERCENTILE_TRAIT_LABELS: Record<DiagnosisTypeCode, string> = {
    stability: "안정성",
    challenge: "도전성",
    teamwork: "협업성",
    individual: "독립 몰입도",
    execution: "실행력",
    planning: "기획력",
    principle: "정밀성",
    flexibility: "유연성",
};
const AXIS_DEFINITIONS: Record<AxisCode, AxisDefinition> = {
    stability: {
        code: "stability",
        leftCode: "stability",
        rightCode: "challenge",
        leftLabel: "안정지향",
        rightLabel: "도전",
    },
    teamwork: {
        code: "teamwork",
        leftCode: "teamwork",
        rightCode: "individual",
        leftLabel: "팀 협업",
        rightLabel: "개인",
    },
    execution: {
        code: "execution",
        leftCode: "execution",
        rightCode: "planning",
        leftLabel: "실행력",
        rightLabel: "기획",
    },
    principle: {
        code: "principle",
        leftCode: "principle",
        rightCode: "flexibility",
        leftLabel: "원칙·꼼꼼함",
        rightLabel: "유연",
    },
};
export async function toDiagnosisResultResponse(result: Awaited<ReturnType<typeof findLatestDiagnosisResultForUser>>): Promise<DiagnosisResultResponseDto> {
    if (!result) {
        throw new Error("Diagnosis result was not found.");
    }
    const axisScores: AxisScores = {
        stability: result.stability_axis_percent,
        teamwork: result.teamwork_axis_percent,
        execution: result.execution_axis_percent,
        principle: result.principle_axis_percent,
    };
    const traitScores = toTraitScores(axisScores);
    const jobCategories = await findJobCategoriesForPersonalityType(result.type_code);
    return {
        runId: result.run_id,
        resultId: result.result_id,
        attemptNo: null,
        typeCode: result.type_code,
        typeName: result.type_name,
        summary: result.summary || "",
        scores: traitScores,
        percentages: traitScores,
        axisResults: toAxisResults(axisScores),
        strengths: Array.isArray(result.strengths) ? result.strengths : [],
        growthPoints: Array.isArray(result.weaknesses) ? result.weaknesses : [],
        recommendations: [],
        jobCategories,
    };
}
function toTraitScores(axisScores: AxisScores): TraitScores {
    return {
        stability: axisScores.stability,
        challenge: 100 - axisScores.stability,
        teamwork: axisScores.teamwork,
        individual: 100 - axisScores.teamwork,
        execution: axisScores.execution,
        planning: 100 - axisScores.execution,
        principle: axisScores.principle,
        flexibility: 100 - axisScores.principle,
    };
}
function toAxisResults(axisScores: AxisScores) {
    return (Object.keys(AXIS_DEFINITIONS) as AxisCode[]).map((code) => {
        const definition = AXIS_DEFINITIONS[code];
        const percent = axisScores[code];
        return {
            code,
            leftLabel: definition.leftLabel,
            rightLabel: definition.rightLabel,
            percent,
            dominantLabel: percent > 55 ? definition.leftLabel : percent < 45 ? definition.rightLabel : "균형",
        };
    });
}
