// Generated by scripts/sync-diagnosis-results.mjs. Do not edit.
import { query } from "@/features/admin/server/db";
export type JobPostingRow = {
    id: string;
    institution_name: string;
    title: string;
    application_end_at: Date | string | null;
    employment_type: string | null;
    work_region: string | null;
    career_requirement: string | null;
    apply_url: string | null;
    categories: string[] | null;
    match_score?: number | string | null;
    is_bookmarked?: boolean;
    ncs_category: string | null;
    job_category?: string | null;
    education_requirement: string | null;
    hiring_count: number | null;
    is_active?: boolean;
    application_start_at?: Date | string | null;
    announcement_at?: Date | string | null;
};
function splitMultiFilter(value?: string) {
    return (value || "")
        .split("|")
        .map((item) => item.trim())
        .filter(Boolean);
}
function buildAnyTextFilter(column: string, value: string | undefined, values: unknown[]) {
    const filters = splitMultiFilter(value);
    if (!filters.length)
        return "";
    const conditions = filters.map((filter) => {
        const param = `$${values.push(`%${filter}%`)}`;
        return `COALESCE(${column}, '') ILIKE ${param}`;
    });
    return `AND (${conditions.join(" OR ")})`;
}
function buildEmploymentTypeFilter(value: string | undefined, values: unknown[]) {
    const filters = splitMultiFilter(value);
    if (!filters.length)
        return "";
    const conditions = filters.map((filter) => {
        if (filter === "정규직") {
            return `(
        ${employmentColumn()} = '정규직'
        OR (
          ${employmentColumn()} ILIKE '%정규%'
          AND ${employmentColumn()} NOT ILIKE '%비정규%'
        )
      )`;
        }
        const param = `$${values.push(`%${filter}%`)}`;
        return `COALESCE(postings.employment_type, '') ILIKE ${param}`;
    });
    return `AND (${conditions.join(" OR ")})`;
}
function employmentColumn() {
    return "COALESCE(postings.employment_type, '')";
}
function normalizeIncludeClosedMonths(value?: number) {
    if (!Number.isFinite(value))
        return 0;
    return Math.min(Math.max(Math.trunc(value || 0), 0), 24);
}
function buildApplicationEndFilter(includeClosedMonths: number, values: unknown[]) {
    if (includeClosedMonths <= 0) {
        return "AND (postings.application_end_at IS NULL OR postings.application_end_at::date >= CURRENT_DATE)";
    }
    const monthsParam = `$${values.push(includeClosedMonths)}`;
    return `
    AND (
      postings.application_end_at IS NULL
      OR postings.application_end_at::date BETWEEN
        (CURRENT_DATE - (${monthsParam}::int * INTERVAL '1 month'))::date
        AND (CURRENT_DATE + (${monthsParam}::int * INTERVAL '1 month'))::date
    )
  `;
}
export async function findRecommendedJobPostings(args: {
    personalityCode: string;
    limit: number;
    offset?: number;
    userId?: string;
    monthlyRegularOnly?: boolean;
    regularOnly?: boolean;
    ncsCategory?: string;
    region?: string;
    employmentType?: string;
    educationRequirement?: string;
    careerRequirement?: string;
    startDate?: string;
    endDate?: string;
    includeClosedMonths?: number;
    sort?: "closing" | "latest" | "views" | "recommended";
}) {
    const values: unknown[] = [args.personalityCode];
    const includeClosedMonths = normalizeIncludeClosedMonths(args.includeClosedMonths);
    const activeFilter = includeClosedMonths > 0 ? "" : "AND postings.is_active = TRUE";
    const categoryFilter = buildAnyTextFilter("categories.name", args.ncsCategory, values);
    const regionFilter = buildAnyTextFilter("postings.work_region", args.region, values);
    const employmentFilter = buildEmploymentTypeFilter(args.employmentType, values);
    const educationFilter = buildAnyTextFilter("postings.education_requirement", args.educationRequirement, values);
    const careerFilter = buildAnyTextFilter("postings.career_requirement", args.careerRequirement, values);
    const startDateFilter = args.startDate
        ? `AND postings.announcement_at::date >= $${values.push(args.startDate)}::date`
        : "";
    const endDateFilter = args.endDate
        ? `AND postings.announcement_at::date <= $${values.push(args.endDate)}::date`
        : "";
    const applicationEndFilter = buildApplicationEndFilter(includeClosedMonths, values);
    const limitParam = `$${values.push(args.limit)}`;
    const userParam = `$${values.push(args.userId || null)}`;
    const offsetParam = `$${values.push(args.offset || 0)}`;
    const regularEmploymentFilter = args.monthlyRegularOnly || args.regularOnly
        ? `AND (
          postings.employment_type = '정규직'
          OR (
            postings.employment_type ILIKE '%정규%'
            AND postings.employment_type NOT ILIKE '%비정규%'
          )
        )`
        : "";
    const monthlyDateFilter = args.monthlyRegularOnly
        ? `AND COALESCE(
          postings.application_start_at,
          postings.announcement_at,
          postings.created_at
        ) < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
        AND COALESCE(postings.application_end_at, 'infinity'::timestamptz)
          >= DATE_TRUNC('month', CURRENT_DATE)`
        : "";
    const orderBy = args.sort === "latest"
        ? "postings.announcement_at DESC NULLS LAST, postings.created_at DESC"
        : args.sort === "views"
            ? "postings.view_count DESC, postings.application_end_at ASC NULLS LAST"
            : `
          MAX(matched_categories.fit_weight) DESC,
          CASE
            WHEN postings.employment_type = '정규직' THEN 0
            WHEN postings.employment_type ILIKE '%정규%'
              AND postings.employment_type NOT ILIKE '%비정규%' THEN 0
            ELSE 1
          END,
          postings.application_end_at ASC NULLS LAST,
          postings.view_count DESC,
          postings.created_at DESC
        `;
    const result = await query<JobPostingRow & {
        total_count: string;
    }>(`
      WITH mapped_categories AS (
        SELECT categories.name, mappings.fit_weight, mappings.sort_order
        FROM public.personality_job_category_mappings mappings
        JOIN public.personality_types personality_types
          ON personality_types.id = mappings.personality_type_id
        JOIN public.job_categories categories
          ON categories.id = mappings.job_category_id
        WHERE personality_types.code = $1
          AND categories.is_active = TRUE
          ${categoryFilter}
        ORDER BY mappings.fit_weight DESC, mappings.sort_order ASC
        LIMIT 6
      ),
      matched_categories AS (
        SELECT
          postings.id AS job_posting_id,
          mapped_categories.name,
          mapped_categories.fit_weight,
          mapped_categories.sort_order
        FROM public.job_postings postings
        JOIN mapped_categories
          ON POSITION(
            REGEXP_REPLACE(mapped_categories.name, '[[:space:]·.]', '', 'g')
            IN REGEXP_REPLACE(COALESCE(postings.ncs_category, ''), '[[:space:]·.]', '', 'g')
          ) > 0
      )
      SELECT
        postings.id,
        COALESCE(institutions.name, postings.raw_payload->'list'->>'instNm', '기관 미정') AS institution_name,
        postings.title,
        postings.application_start_at,
        postings.application_end_at,
        postings.employment_type,
        postings.work_region,
        postings.career_requirement,
        postings.apply_url,
        postings.ncs_category,
        postings.education_requirement,
        postings.hiring_count,
        postings.is_active,
        COUNT(*) OVER() AS total_count,
        (
          ${userParam}::uuid IS NOT NULL
          AND EXISTS (
            SELECT 1
            FROM public.user_job_bookmarks bookmarks
            WHERE bookmarks.user_id = ${userParam}::uuid
              AND bookmarks.job_posting_id = postings.id
          )
        ) AS is_bookmarked,
        array_agg(DISTINCT matched_categories.name ORDER BY matched_categories.name) AS categories,
        MAX(matched_categories.fit_weight)::integer AS match_score
      FROM public.job_postings postings
      JOIN matched_categories
        ON matched_categories.job_posting_id = postings.id
      LEFT JOIN public.public_institutions institutions
        ON institutions.id = postings.institution_id
      WHERE TRUE
        ${activeFilter}
        ${applicationEndFilter}
        ${regularEmploymentFilter}
        ${monthlyDateFilter}
        ${regionFilter}
        ${employmentFilter}
        ${educationFilter}
        ${careerFilter}
        ${startDateFilter}
        ${endDateFilter}
      GROUP BY postings.id, institutions.name
      ORDER BY ${orderBy}
      LIMIT ${limitParam}
      OFFSET ${offsetParam}
    `, values);
    return {
        rows: result.rows,
        total: Number(result.rows[0]?.total_count || 0),
    };
}
