// Generated by scripts/sync-diagnosis-results.mjs. Do not edit.
import type { JobPostingDto } from "./jobs.dto";
import { type JobPostingRow } from "./jobs.repository";
export function toJobPostingDto(row: JobPostingRow): JobPostingDto {
    const applicationStartAt = row.application_start_at
        ? new Date(row.application_start_at).toISOString()
        : null;
    const applicationEndAt = row.application_end_at
        ? new Date(row.application_end_at).toISOString()
        : null;
    return {
        id: row.id,
        institutionName: row.institution_name,
        title: row.title,
        applicationStartAt,
        applicationEndAt,
        dday: toDday(applicationEndAt),
        employmentType: row.employment_type,
        region: row.work_region,
        careerRequirement: row.career_requirement,
        applyUrl: row.apply_url,
        categories: row.categories || [],
        isBookmarked: Boolean(row.is_bookmarked),
        ncsCategory: row.ncs_category,
        educationRequirement: row.education_requirement,
        hiringCount: row.hiring_count,
        isClosed: row.is_active === false ||
            Boolean(applicationEndAt && isPastApplicationEndDate(applicationEndAt)),
        ...(row.match_score == null
            ? {}
            : { matchScore: Number(row.match_score) }),
    };
}
const SEOUL_TIME_ZONE = "Asia/Seoul";
const DAY_IN_MS = 86400000;
const seoulDateFormatter = new Intl.DateTimeFormat("en-US", {
    timeZone: SEOUL_TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
});
function toDday(value: string | null) {
    if (!value)
        return "상시";
    const days = daysUntilSeoulDate(value);
    if (days == null)
        return "상시";
    return days === 0 ? "D-Day" : `D-${days}`;
}
function isPastApplicationEndDate(value: string) {
    const endDay = toSeoulDayNumber(value);
    const todayDay = toSeoulDayNumber(new Date());
    return endDay != null && todayDay != null && endDay < todayDay;
}
function daysUntilSeoulDate(value: string) {
    const endDay = toSeoulDayNumber(value);
    const todayDay = toSeoulDayNumber(new Date());
    if (endDay == null || todayDay == null)
        return null;
    return Math.max(0, endDay - todayDay);
}
function toSeoulDayNumber(value: string | Date) {
    const date = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(date.getTime()))
        return null;
    const parts = seoulDateFormatter.formatToParts(date);
    const year = Number(parts.find((part) => part.type === "year")?.value);
    const month = Number(parts.find((part) => part.type === "month")?.value);
    const day = Number(parts.find((part) => part.type === "day")?.value);
    if (!year || !month || !day)
        return null;
    return Math.floor(Date.UTC(year, month - 1, day) / DAY_IN_MS);
}
